version: '3.9'
services:
  frontend-app:
    image: daininlucas/girc-prac-frontend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.tipo == frontend
    init: true
    networks:
      - girc_network
    ports:
      - 80:8080
  backend-app:
    image: daininlucas/girc-prac-backend
    deploy:
      mode: replicated
      replicas: 3
    init: true
    networks:
      - girc_network
    ports:
      - 5000:5000
networks:
  girc_network:
    driver: overlay

